highlight/highlight/urls.py
from django.contrib import admin
from django.urls import path, include
import portfolio, user


urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls')),
    path('user/', include('user.urls', namespace="user")),
    

]

highlight/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mypage/', views.mypage, name='mypage'),
]

highlight/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title>base</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
 		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
 		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="{% static 'css/base.css' %}" />
	</head>

	<body>
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container-fluid">
				<div class="col-lg-4 navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'main' %}">
						<img class="logo" src="{% static 'img/highlight_logo.png' %}" alt="highlight_logo">
					</a>
				</div>
				{% if user.is_active %}
				<div class="collapse navbar-collapse" id="myNavbar">					
					<ul class="nav navbar-nav navbar-right">
						<li><p>{{user.username}}님, 어서오세요!<p></li>
						<li><a href="#">편집자 찾기</a></li>
						<li><a href="{% url 'user:mypage' %}">마이페이지</a></li>
						<li><a href="{% url 'user:logout' %}">로그아웃</a></li>
						{% comment %} href={% url '앱이름:urls.py에서 지정한 url name'%} {% endcomment %}
					</ul>
				</div>
				{% else %}
				<div class="collapse navbar-collapse" id="myNavbar">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#">편집자 찾기</a></li>
						<li><a href="{% url 'user:login' %}">로그인</a></li>
						<li><a href="{% url 'user:signup' %}">회원가입</a></li>
						{% comment %} href={% url '앱이름:urls.py에서 지정한 url name'%} {% endcomment %}
					</ul>
				</div>
				{% endif %}
			</div>
		</nav>

        {% block content %}
        {% endblock %}
	</body>
</html>