highlight/highlight/urls.py
from django.contrib import admin
from django.urls import path, include
import portfolio, user


urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls')),
    path('user/', include('user.urls', namespace="user")),
    

]

highlight/portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name = 'main'),
    path('<int:portfolio_id>/', views.detail, name = 'detail'),
    path('new/', views.portfolio_new, name = 'new'),
    path('<int:portfolio_id>/edit/', views.portfolio_edit, name = 'edit'),
    path('<int:portfolio_id>/delete/', views.portfolio_delete, name = 'delete'),
    path('<int:portfolio_id>/review_new/', views.review_new, name = 'review_new'),
    path('<int:review_id>/review_delete/', views.review_delete, name = 'review_delete'),

]

highlight/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mypage/', views.mypage, name='mypage'),
]

highlight/portfolio/models.py
from django.db import models
from django.utils import timezone
from user.models import User

# Create your models here.

class Portfolio(models.Model):
    editor = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 100)
    content = models.TextField()
    production = models.CharField(max_length=20)
    profile = models.ImageField(blank = True)
    price = models.CharField(max_length = 20)
    career = models.TextField(blank = True)
    grade = models.FloatField(default=0)
    
    def __str__(self):
        return self.title

class Review(models.Model):
    writer = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.TextField(blank = False)
    grade = models.FloatField(default=0)
    published_date = models.DateTimeField(default = timezone.now)
    portfolio = models.ForeignKey(Portfolio, on_delete = models.CASCADE)

    def __str__(self):
        return self.writer





highlight/portfolio/forms.py
from django import forms
from .models import Portfolio, Review

class PortfolioForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = {'title', 'content', 'production', 'profile', 'price', 'career', }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = {'content', 'grade', }

highlight/portfolio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Portfolio, Review
from django.utils import timezone
from .forms import PortfolioForm, ReviewForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Avg

# Create your views here.
def main(request):
    portfolio = Portfolio.objects.all()
    paginator = Paginator(portfolio, 5)
    page = request.GET.get('page')
    portfolio = paginator.get_page(page)

    return render(request, 'portfolio/portfolio_main.html', {'portfolio' : portfolio})

def detail(request, portfolio_id):
    portfolio_detail = get_object_or_404(Portfolio, pk = portfolio_id)
    reviewForm = ReviewForm()
    reviews = Review.objects.filter(portfolio_id= portfolio_id).order_by()

    average = reviews.aggregate(Avg("grade"))["grade__avg"]
    if average == None:
        average = 0
    average = round(average,2)
    
    portfolio_detail.grade = average
    
    return render(request, 'portfolio/portfolio_detail.html', {'portfolio' : portfolio_detail, 'reviewForm' : reviewForm, 'average' : average})

def portfolio_new(request):
    if request.user.user_type == 'editor': 
        if request.method == "POST":
            form = PortfolioForm(request.POST)
            if form.is_valid():
                portfolio = form.save(commit=False)
                portfolio.editor = request.user
                portfolio.save()
                return redirect('detail', portfolio_id = portfolio.pk)
        else:
            form = PortfolioForm()
        return render(request, 'portfolio/portfolio_new.html', {'form': form})
    else :
        return redirect('main')

def portfolio_edit(request, portfolio_id):
    portfolio = get_object_or_404(Portfolio, pk = portfolio_id)
    if request.user.user_type == 'editor':
        if request.method == "POST":
            form = PortfolioForm(request.POST, instance = portfolio)
            if form.is_valid():
                portfolio = form.save(commit=False)
                portfolio.save()
                return redirect('detail', portfolio_id = portfolio.pk)
        else:
            form = PortfolioForm(instance = portfolio)
        return render(request, 'portfolio/portfolio_edit.html', {'form':form})
    else:
        return redirect('detail', portfolio_id = portfolio.pk)

def portfolio_delete(request, portfolio_id):
    portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
    if request.user.user_type == 'editor':
        portfolio.delete()
        return redirect('main')
    else:
        return redirect('detail', portfolio_id = portfolio.pk)

@login_required(login_url='/user/login/')
def review_new(request, portfolio_id):
    portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit = False)
            review.portfolio = get_object_or_404(Portfolio, pk = portfolio_id)
            review.writer = request.user
            review.save()
            return redirect('detail', portfolio_id= portfolio_id)
    else:
        return redirect('detail', portfolio_id = portfolio.pk)

def review_delete(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    portfolio = review.portfolio
    review.delete()
    return redirect('detail', portfolio_id=portfolio.id)




highlight/templates/portfolio/detail.html
  {% extends 'base.html' %}
  {% block content %}
    <h1>포트폴리오 디테일 페이지</h1>
        <div>
            <h2>{{portfolio.title}}</h2>
            <p>{{portfolio.profile}}</p>
            <p>편집자: {{portfolio.editor}}</p>
            <p>{{portfolio.production}}</p>
            <p>{{portfolio.content}}</p>
            <p>평점: {{portfolio.grade}}</p>
            <p>가격: {{portfolio.price}}</p>
        </div> 
  {% endblock %}

highlight/templates/portfolio/portfolio_detail.html
  {% extends 'base.html' %}
  {% block content %}
        <div>
            <h2>{{portfolio.title}}</h2>
            <p>평점: {{average}}</p>
            <p>약력: {{portfolio.career}}</p>
            <p>편집자: {{portfolio.editor}}</p>
            <p>영상: {{portfolio.production}}</p>
            <p>내용: {{portfolio.content}}</p>
            <p>가격: {{portfolio.price}}</p>
            <a href = "{% url 'main' %}">메인</a>
            {% if user.id == portfolio.editor.id %}
            <a href = "{% url 'edit' portfolio.id %}">수정</a>
            <a href = "{% url 'delete' portfolio.id %}">삭제</a>
            {% endif %}
        </div> 

        <hr>
        
        <h5>후기</h5>
        {% for review in portfolio.review_set.all %}
        <h4>{{review.content}}</h4>
        <p>작성자: {{review.writer}}</p>
        <p>작성일: {{review.published_date}}</p>
        <p>평점: {{review.grade}}</p>
        {% if user.id == review.writer.id %}
        <p><a href="{% url 'review_delete' review_id=review.id %}">삭제</a></p>
        {% endif %}
        {% endfor %}
        <form action = "{% url 'review_new' portfolio.pk %}" method = "POST">
          {% csrf_token %}
          {{reviewForm}}
          <input type = "submit">
        </form>
  {% endblock %}

highlight/templates/portfolio/portfolio_edit.html
{% extends 'base.html' %}
{% block content %}
  <div>
      <h1>포트폴리오 수정 페이지</h1>
      <form method = "POST">
          {% csrf_token %}
          {{ form.as_p}}
          <button type = "submit">저장</button>
      </form>
    </div>
{% endblock %}

highlight/templates/portfolio/portfolio_main.html
{% extends 'base.html' %}
{% block content %}

{% load static %}

<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
<!-- Custom styles for this template -->

<link href="portfolio_main.css" rel="stylesheet">


{% if user.user_type == 'editor' %}
<h2><a href = "{% url 'new' %}">포트폴리오 생성하기</a></h2>
{% endif %}

<body>
	<!-- Banner -->
	<div class="banner">
    <div class="banner-image"><img src="{% static 'img/banner.jpg' %}" alt="banner.jpg"></div>
    <div class="banner-content">      
      <h1>Make your own Highlight</h1>
      <p>당신만의 하이라이트가 필요한가요?</p>
      <p>여러분의 평범한 풋살 경기, 특별한 순간으로 만들어드립니다.</p>
      <br>
      <p>저희와 함께 하이라이트 하세요</p> 
    </div>
	</div>

  {% for portfolio in portfolio %}
  <hr class="featurette-divider">
  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading"><a href = "{% url 'detail' portfolio.id %}"> {{portfolio.title}} </a>  </h2>
      <p class="lead">작성자: {{portfolio.editor}} <br> 평점: {{portfolio.grade}} <br> 내용: {{portfolio.content}} <br> 가격: {{portfolio.price}}</bt></p>
    </div>
    <div class="col-md-5">
      <img class="lead" width="600" height="400" src = "https://postfiles.pstatic.net/MjAyMDEwMjNfNzgg/MDAxNjAzNDM3OTI3Mzc2.kQDj2E4xy5jtGLauYTbXpG6crAqm2rCSa5x18Qw5Uoog.ZJcJc6_XjKYuXezKyLDfsOeHBXxGKajonR607QoV62Yg.JPEG.kippsr3/%EC%9C%A0%ED%8A%9C%EB%B8%8C2.jpg?type=w773" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" alt="video"><rect width="100%" height="100%" fill="#eee"/></img>
    </div>
  </div>
  {% endfor %}
  <hr class="featurette-divider">

  <div>
      <div class = "pagination">
        {% if portfolio.has_previous %}
          <a href="?page=1"> << </a>
          <a href="?page={{ portfolio.previous_page_number }}"> < </a>
        {% endif %}

        {% for num in portfolio.paginator.page_range %}
          {% if portfolio.number == num %}
            <strong>{{ num }}</strong>
        {% elif num > portfolio.number|add:'-2' and num < portfolio.number|add:'2' %}
            {{ num }}
          {% endif %}
        {% endfor %}
        
        {% if portfolio.has_next %}
          <a href="?page={{ portfolio.next_page_number }}"> > </a>
          <a href="?page={{ portfolio.paginator.num_pages }}"> >> </a>
        {% endif %}
      </div>
  </div>
{% endblock %}
</body>

highlight/templates/portfolio/portfolio_new.html
  {% extends 'base.html' %}
  {% block content %}
    <div>
      {% if user.user_type == 'editor' %}
        <h1>포트폴리오 제작 페이지</h1>
        <form method = "POST">
            {% csrf_token %}
            {{ form.as_p}}
            <button type = "submit">저장</button>
        </form>
      {% endif %}
    </div>
  {% endblock %}